// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseWorkflowFile() {
  return window['go']['main']['App']['BrowseWorkflowFile']();
}

export function CheckComfyUI() {
  return window['go']['main']['App']['CheckComfyUI']();
}

export function ClearBackground() {
  return window['go']['main']['App']['ClearBackground']();
}

export function ClearStoryCoverImage(arg1) {
  return window['go']['main']['App']['ClearStoryCoverImage'](arg1);
}

export function CreateStory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateStory'](arg1, arg2, arg3);
}

export function CreateUserTemplate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['CreateUserTemplate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function DeleteStory(arg1) {
  return window['go']['main']['App']['DeleteStory'](arg1);
}

export function DeleteUserTemplate(arg1) {
  return window['go']['main']['App']['DeleteUserTemplate'](arg1);
}

export function GenerateImage(arg1, arg2) {
  return window['go']['main']['App']['GenerateImage'](arg1, arg2);
}

export function GenerateStoryIdea(arg1) {
  return window['go']['main']['App']['GenerateStoryIdea'](arg1);
}

export function GetActiveModel() {
  return window['go']['main']['App']['GetActiveModel']();
}

export function GetBackground() {
  return window['go']['main']['App']['GetBackground']();
}

export function GetComfyConfig() {
  return window['go']['main']['App']['GetComfyConfig']();
}

export function GetComfyModels() {
  return window['go']['main']['App']['GetComfyModels']();
}

export function GetModelConfig(arg1) {
  return window['go']['main']['App']['GetModelConfig'](arg1);
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetStories() {
  return window['go']['main']['App']['GetStories']();
}

export function GetStory(arg1) {
  return window['go']['main']['App']['GetStory'](arg1);
}

export function GetUserTemplates() {
  return window['go']['main']['App']['GetUserTemplates']();
}

export function PickBackgroundImage() {
  return window['go']['main']['App']['PickBackgroundImage']();
}

export function PickStoryCoverImage(arg1) {
  return window['go']['main']['App']['PickStoryCoverImage'](arg1);
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function SaveComfyConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SaveComfyConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SaveModelConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveModelConfig'](arg1, arg2, arg3, arg4);
}

export function SaveSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2, arg3);
}

export function SetActiveModel(arg1) {
  return window['go']['main']['App']['SetActiveModel'](arg1);
}

export function StreamMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StreamMessage'](arg1, arg2, arg3, arg4);
}

export function UpdateStory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateStory'](arg1, arg2, arg3, arg4);
}

export function UpdateStorySettings(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateStorySettings'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateStoryStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateStoryStatus'](arg1, arg2);
}
