// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function BrowseWorkflowFile():Promise<string>;

export function CheckComfyUI():Promise<boolean>;

export function ClearBackground():Promise<void>;

export function ClearStoryCoverImage(arg1:string):Promise<store.Story>;

export function CreateStory(arg1:string,arg2:string,arg3:string):Promise<store.Story>;

export function CreateUserTemplate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string):Promise<store.UserTemplate>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function DeleteStory(arg1:string):Promise<void>;

export function DeleteUserTemplate(arg1:string):Promise<void>;

export function GenerateImage(arg1:string,arg2:string):Promise<string>;

export function GenerateStoryIdea(arg1:string):Promise<string>;

export function GetActiveModel():Promise<string>;

export function GetBackground():Promise<string>;

export function GetComfyConfig():Promise<main.ComfyConfig>;

export function GetComfyModels():Promise<Array<string>>;

export function GetModelConfig(arg1:string):Promise<main.ModelConfig>;

export function GetOllamaModels():Promise<Array<main.OllamaModel>>;

export function GetSessions(arg1:string):Promise<Array<store.Session>>;

export function GetStories():Promise<Array<store.Story>>;

export function GetStory(arg1:string):Promise<store.Story>;

export function GetUserTemplates():Promise<Array<store.UserTemplate>>;

export function PickBackgroundImage():Promise<string>;

export function PickStoryCoverImage(arg1:string):Promise<store.Story>;

export function PullModel(arg1:string):Promise<void>;

export function SaveComfyConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:number):Promise<void>;

export function SaveModelConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveSession(arg1:string,arg2:string,arg3:string):Promise<store.Session>;

export function SetActiveModel(arg1:string):Promise<void>;

export function StreamMessage(arg1:string,arg2:Array<main.ChatMessage>,arg3:string,arg4:string):Promise<void>;

export function UpdateStory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<store.Story>;

export function UpdateStorySettings(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string,arg6:string,arg7:string):Promise<store.Story>;

export function UpdateStoryStatus(arg1:string,arg2:string):Promise<store.Story>;
