// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

function invoke(method, args = []) {
  const app = typeof window !== 'undefined' ? window?.go?.main?.App : undefined;
  const fn = app?.[method];

  if (typeof fn !== 'function') {
    // Allow the web/Next.js preview to run without the Wails bridge.
    const fallbackByMethod = {
      CheckComfyUI: false,
      GetActiveModel: '',
      GetBackground: '',
      GetComfyConfig: {
        url: 'http://127.0.0.1:8000',
        model: '',
        steps: 20,
        cfg: 7,
        width: 512,
        height: 768,
        negativePrompt: '',
        workflowPath: '',
        positiveNodeID: ''
      },
      GetComfyModels: [],
      GetModelConfig: {
        aiInstructions: '',
        storyInstructions: '',
        authorNotes: ''
      },
      GetOllamaModels: [],
      GetSessions: [],
      GetStories: [],
      GetStory: null,
      GetUserTemplates: []
    };

    return Promise.resolve(fallbackByMethod[method]);
  }

  return fn(...args);
}

export function BrowseWorkflowFile() {
  return invoke('BrowseWorkflowFile');
}

export function CheckComfyUI() {
  return invoke('CheckComfyUI');
}

export function ClearBackground() {
  return invoke('ClearBackground');
}

export function ClearStoryCoverImage(arg1) {
  return invoke('ClearStoryCoverImage', [arg1]);
}

export function CreateStory(arg1, arg2, arg3) {
  return invoke('CreateStory', [arg1, arg2, arg3]);
}

export function CreateUserTemplate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return invoke('CreateUserTemplate', [arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12]);
}

export function DeleteModel(arg1) {
  return invoke('DeleteModel', [arg1]);
}

export function DeleteSession(arg1, arg2) {
  return invoke('DeleteSession', [arg1, arg2]);
}

export function DeleteStory(arg1) {
  return invoke('DeleteStory', [arg1]);
}

export function DeleteUserTemplate(arg1) {
  return invoke('DeleteUserTemplate', [arg1]);
}

export function GenerateImage(arg1, arg2) {
  return invoke('GenerateImage', [arg1, arg2]);
}

export function GenerateStoryIdea(arg1) {
  return invoke('GenerateStoryIdea', [arg1]);
}

export function GetActiveModel() {
  return invoke('GetActiveModel');
}

export function GetBackground() {
  return invoke('GetBackground');
}

export function GetComfyConfig() {
  return invoke('GetComfyConfig');
}

export function GetComfyModels() {
  return invoke('GetComfyModels');
}

export function GetModelConfig(arg1) {
  return invoke('GetModelConfig', [arg1]);
}

export function GetOllamaModels() {
  return invoke('GetOllamaModels');
}

export function GetSessions(arg1) {
  return invoke('GetSessions', [arg1]);
}

export function GetStories() {
  return invoke('GetStories');
}

export function GetStory(arg1) {
  return invoke('GetStory', [arg1]);
}

export function GetUserTemplates() {
  return invoke('GetUserTemplates');
}

export function PickBackgroundImage() {
  return invoke('PickBackgroundImage');
}

export function PickStoryCoverImage(arg1) {
  return invoke('PickStoryCoverImage', [arg1]);
}

export function PullModel(arg1) {
  return invoke('PullModel', [arg1]);
}

export function SaveComfyConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return invoke('SaveComfyConfig', [arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9]);
}

export function SaveModelConfig(arg1, arg2, arg3, arg4) {
  return invoke('SaveModelConfig', [arg1, arg2, arg3, arg4]);
}

export function SaveSession(arg1, arg2, arg3) {
  return invoke('SaveSession', [arg1, arg2, arg3]);
}

export function SetActiveModel(arg1) {
  return invoke('SetActiveModel', [arg1]);
}

export function StreamMessage(arg1, arg2, arg3, arg4) {
  return invoke('StreamMessage', [arg1, arg2, arg3, arg4]);
}

export function UpdateStory(arg1, arg2, arg3, arg4) {
  return invoke('UpdateStory', [arg1, arg2, arg3, arg4]);
}

export function UpdateStorySettings(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return invoke('UpdateStorySettings', [arg1, arg2, arg3, arg4, arg5, arg6, arg7]);
}

export function UpdateStoryStatus(arg1, arg2) {
  return invoke('UpdateStoryStatus', [arg1, arg2]);
}
